### ISSUE TITLE
Profile and measure performance of optimized Exact BR Compute Loop

### ISSUE THREAD

**Issue by patrickb314** [CUP-ECS/beatnik#20]
If Kokkos primitives can be used to optimize the Exact Birchoff-Rott velocity calculation (see issue #19), test and profile the resulting performance once these optimizations are done.

**Comment by patrickb314** [comment]
Haven't yet used Kokkos TeamPolicy primitives, #28 made some improvements to loop performance.

**Comment by patrickb314** [comment]
#93 takes care of the optimization, now just the profiling is needed.

**Comment by JStewart28** [comment]
Profiling completed
